### ISSUE TITLE
Question: how to make java in current directory/project visible?

### ISSUE THREAD

**Issue by sakovias** [SublimeLinter/SublimeLinter-javac#13] opened 2017-05-06 12:35 UTC
This should be a very straightforward issue, but I can't seem to find a solution. I'd appreciate some help a lot!

In my current project I have two Java files: `Point.java` and `LineSegment.java`. The `LineSegment` class uses the `Point` class; since they are in the same directory `LineSegment` doesn't have to import `Point`. Both `Point` and `LineSegment` compile without any issues.

However, when I open `LineSegment.java` in Sublime, all references to `Point` are highlighted in red and `cannot find symbol` error is issued.

Any ideas on how I can fix this?

My project settings:
``` json
{
  "folders":
  [
    {
      "path": "/home/anton/calc/algorithms/homework/week3"
    }
  ],
  "SublimeLinter":
  {
    "linters":
    {
      "javac": {
        "lint": "all",
        "args": [
          "-encoding", "UTF8",
          "-cp", "/usr/local/algs4/algs4.jar"
        ]
      }
    }
  }
}
```

Here's the visual trace:

![sublime-javac-issue](https://cloud.githubusercontent.com/assets/4750367/25772339/9637c926-3236-11e7-9d48-7b46ae62ad0d.png)

**Comment by renatosc** [comment] 2018-07-08 18:31
+1

**Comment by kaste** [comment] 2018-07-08 20:02
This looks like a duplicate of #20

**Closed** 2018-12-18 19:15 UTC
Labels: question
